name: Lint

on:
  workflow_call:

permissions:
  checks: write
  contents: read

jobs:
  lint:
    name: lint checks
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up make
        run: sudo apt update && sudo apt install -y make

      - name: Run lint checks
        run: make lint
